### ISSUE TITLE
click 'OK' ,parent widget pop

### ISSUE THREAD

**Issue by magicvz** [best-flutter/easy_alert#3]

**Comment by ExtraSettings** [comment]
To give more context. There's an issue when clicking `OK` on an alert would cause your own screen to get popped from the navigator instead of the alert. I had created a PR for it, but it seems like it's not going to be merged soon, so for those looking for a fix, you can use my fork:

```yaml
dependencies:
  easy_alert:
    git: git@github.com:Sayegh7/easy_alert.git
```
